[tox]
minversion = 4.19
envlist = 
    {py312}-{django50,django51,django52,django60}
    {py313}-{django50,django51,django52,django60}
    {py314}-{django50,django51,django52,django60}
    type
    clean


[testenv]
commands = pytest --cov --cov-append --cov-report xml {posargs}
description = Running tests under {base_python}
envdir = {toxworkdir}/venvs/{envname}
setenv =
    PYTHONDONTWRITEBYTECODE=1
    PYTHONWARNINGS=once
dependency_groups =
    test
    django50: django50
    django51: django51
    django52: django52
    django60: django60


[testenv:type]
description = Run type check
skip_install = True
passenv =
    PYTHONDONTWRITEBYTECODE=1
    TERM
    MYPY_FORCE_COLOR
    MYPY_FORCE_TERMINAL_WIDTH
deps =
    flake8
    flake8-quotes
    flake8-tidy-imports
    pep8
    mypy
    django-stubs[compatible-mypy]
    djangorestframework-stubs[compatible-mypy]
commands =
    mypy .
    flake8 .
